# Generated by Django 4.1.1 on 2022-09-20 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryFood', '0002_orders_dateorder_orders_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='dateorder',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0), help_text='Дата заказа'),
        ),
    ]
