# Generated by Django 4.1.1 on 2022-11-01 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DeliveryFood', '0003_alter_orders_dateorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(help_text='Улица', max_length=50, verbose_name='name_street')),
                ('build', models.CharField(help_text='Дом', max_length=50, verbose_name='name_build')),
                ('flat', models.IntegerField(help_text='Квартира', verbose_name='name_flat')),
                ('user_id', models.ForeignKey(help_text='ID пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adress',
                'db_table': 'Adresses',
            },
        ),
    ]
